version: 0.2

phases:
  pre_build:
    commands:
      - apt update
      - lscpu
      - 
  build:
    commands:
      - docker version
      - 
  post_build:
    commands:
      - echo Performance test complete
