version: 0.2

phases:
  pre_build:
    commands:
      - apt update
      - docker pull loadimpact/k6
  build:
    commands:
      - echo Run performance test
      - docker run -i loadimpact/k6 run - <scripts/test.js
  post_build:
    commands:
      - echo Performance test complete
